export {
  applyTimelineEdits,
  clampPercent,
  normalizeSections,
  layoutsToEdits,
  createTimelineEdits,
  resizeSectionEdge,
  splitSectionAt,
  nextSplitSectionId,
  setPlayheadEdit,
  toggleLaneMute,
  toggleLaneSolo,
  trimSectionEdit,
  moveSection,
  addOrUpdateMarker,
  removeMarker,
  setLoopRegion,
  recordTimelineEdit,
  undoTimelineEdit,
  redoTimelineEdit,
  canUndoTimeline,
  canRedoTimeline,
  type SectionLayout,
  type TimelineHistory,
} from "@pulseforge/shared/lib/studio/timeline-edits";

export {
  clearTimelineHistory,
  loadTimelineHistory,
  resolveTimelineHistory,
  saveTimelineHistory,
  timelineHistoryKey,
} from "@pulseforge/shared/lib/studio/timeline-history-persist";