
import { useState } from "react";
import { Download, FileText } from "lucide-react";
import type { TrackAnalysis } from "@/types";
import { formatNumber } from "@/lib/utils";

interface ExportReportProps {
  analysis: TrackAnalysis;
}

export function ExportReport({ analysis }: ExportReportProps) {
  const [exporting, setExporting] = useState(false);

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPdf = async () => {
    setExporting(true);
    try {
      const jspdfPkg = "jspdf";
      const { jsPDF } = await import(/* @vite-ignore */ jspdfPkg);
      const doc = new jsPDF({ unit: "pt", format: "a4" });
      const margin = 48;
      let y = margin;
      const line = (text: string, size = 11, bold = false) => {
        doc.setFontSize(size);
        doc.setFont("helvetica", bold ? "bold" : "normal");
        const lines = doc.splitTextToSize(text, 500);
        doc.text(lines, margin, y);
        y += lines.length * (size + 4);
        if (y > 760) {
          doc.addPage();
          y = margin;
        }
      };

      line("PulseForge — Pre-Release Intelligence Report", 18, true);
      y += 8;
      line(`${analysis.track.title} by ${analysis.track.artist}`, 14, true);
      if (analysis.track.album) line(`Album: ${analysis.track.album}`, 10);
      if (analysis.track.genre) line(`Genre: ${analysis.track.genre}`, 10);
      y += 12;

      line("HIT POTENTIAL SCORE", 12, true);
      line(`Overall: ${analysis.hitPotential.overall}/100 (${analysis.hitPotential.verdict})`, 11);
      line(`Beat Fit: ${analysis.hitPotential.breakdown.beatFit} | Lyric Virality: ${analysis.hitPotential.breakdown.lyricVirality}`, 10);
      line(`Trend Alignment: ${analysis.hitPotential.breakdown.trendAlignment} | Hook: ${analysis.hitPotential.breakdown.hookStrength}`, 10);
      y += 10;

      line("LYRICS & HOOK", 12, true);
      line(`Hook: "${analysis.lyrics.hookLine}"`, 10);
      line(`Hook Strength: ${analysis.lyrics.hookStrength} | Sentiment: ${analysis.lyrics.sentiment}`, 10);
      line(`Themes: ${analysis.lyrics.themes.join(", ")}`, 10);
      y += 10;

      line("1M LISTENER SIMULATION", 12, true);
      line(`Probability to reach 1M: ${analysis.simulation.probabilityToReach}%`, 10);
      line(`Median weeks: ${analysis.simulation.medianWeeks} | Projected peak: ${formatNumber(analysis.simulation.projectedPeak)}`, 10);
      y += 10;

      line("ENERGY PROFILE (Cyanite)", 12, true);
      line(`BPM: ${analysis.energy.bpm} | Energy: ${Math.round(analysis.energy.energy * 100)}% | Danceability: ${Math.round(analysis.energy.danceability * 100)}%`, 10);
      if (analysis.energy.moodTags?.length) {
        line(`Moods: ${analysis.energy.moodTags.join(", ")}`, 10);
      }
      y += 10;

      if (analysis.streaming) {
        line("STREAMING (Songstats)", 12, true);
        if (analysis.streaming.available) {
          line(`Velocity: ${analysis.streaming.velocityScore} | Streams: ${analysis.streaming.totalStreams.toLocaleString()} | Playlists: ${analysis.streaming.totalPlaylists}`, 10);
        } else {
          line("Pre-release — no streaming data yet", 10);
        }
        y += 10;
      }

      line("MARKETING RECOMMENDATIONS", 12, true);
      analysis.recommendations.forEach((rec, i) => {
        line(`${i + 1}. [${rec.priority.toUpperCase()}] ${rec.title}`, 10, true);
        line(rec.description, 9);
        y += 4;
      });

      y += 16;
      line("Generated by PulseForge · Powered by Musixmatch Pro API", 8);
      line("Musicathon 2026", 8);

      doc.save(`pulseforge-${analysis.track.title.replace(/\s+/g, "-").toLowerCase()}.pdf`);
    } catch {
      alert("PDF export is unavailable in this environment. Use Print instead.");
    } finally {
      setExporting(false);
    }
  };

  return (
    <>
      <div className="flex flex-wrap gap-2 sm:justify-end" data-print-hide>
        <button
          type="button"
          onClick={handleDownloadPdf}
          disabled={exporting}
          className="inline-flex items-center gap-2 rounded-xl border border-accent/30 bg-accent-muted px-4 py-2 text-sm font-medium text-accent-light transition hover:bg-accent/20 disabled:opacity-50"
        >
          <Download className="h-4 w-4" />
          {exporting ? "Generating…" : "Download PDF"}
        </button>
        <button
          type="button"
          onClick={handlePrint}
          className="inline-flex items-center gap-2 rounded-xl border border-border bg-surface-elevated px-4 py-2 text-sm font-medium text-muted transition hover:border-purple/30 hover:text-foreground"
        >
          <FileText className="h-4 w-4" />
          Print
        </button>
      </div>

      {/* Print-only report */}
      <div className="hidden print:block print-report">
        <h1>PulseForge Report</h1>
        <h2>{analysis.track.title} — {analysis.track.artist}</h2>
        <p>Hit Potential: {analysis.hitPotential.overall}/100</p>
        <p>1M Probability: {analysis.simulation.probabilityToReach}%</p>
        <p>Hook: &ldquo;{analysis.lyrics.hookLine}&rdquo;</p>
      </div>
    </>
  );
}